export const ROUTES = {
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  HOME: 'Home',
  SEARCH: 'Search',
  PROPERTY_LIST: 'PropertyList',
  PROPERTY_DETAIL: 'PropertyDetail',
  SAVED: 'Saved',
  NOTIFICATIONS: 'Notifications',
  PROFILE: 'Profile',
  CONTACT_AGENT: 'ContactAgent',
  BOOK_VISIT: 'BookVisit',
  MAP_SEARCH: 'MapSearch',
  COMPARE_PROPERTIES: 'CompareProperties',
  MY_INQUIRIES: 'MyInquiries',
  HELP_CENTER: 'HelpCenter',
  REPORT_LISTING: 'ReportListing',
  SETTINGS: 'Settings',
} as const;
