import { ROUTES } from '../constants/routes';

export const TAB_ROUTES = [
  ROUTES.HOME,
  ROUTES.SEARCH,
  ROUTES.SAVED,
  ROUTES.NOTIFICATIONS,
  ROUTES.PROFILE,
] as const;

export const STACK_ROUTES = [
  ROUTES.PROPERTY_DETAIL,
  ROUTES.CONTACT_AGENT,
  ROUTES.BOOK_VISIT,
  ROUTES.MAP_SEARCH,
  ROUTES.COMPARE_PROPERTIES,
  ROUTES.MY_INQUIRIES,
  ROUTES.HELP_CENTER,
  ROUTES.REPORT_LISTING,
  ROUTES.SETTINGS,
] as const;
